python src/main.py --config=ippo_pretr      --env-config=doubleref_ood_train with notes="ippo pretrain on doubleref with last button disabled"
# python src/main.py --config=ippo_r_pretr    --env-config=doubleref_ood_train with notes="ippo+r pretrain on doubleref with last button disabled"
# python src/main.py --config=ippo_ues_pretr  --env-config=doubleref_ood_train with notes="ippo+ues pretrain on doubleref with last button disabled"
# python src/main.py --config=ippo_uesr_pretr --env-config=doubleref_ood_train with notes="ippo+uesr pretrain on doubleref with last button disabled"

# python src/main.py --config=ippo_down      --env-config=doubleref_ood_test_02 with load_step=1000000 notes="ippo downstream on doubleref k=0.2" checkpoint_path=""
# python src/main.py --config=ippo_r_down    --env-config=doubleref_ood_test_02 with load_step=1000000 notes="ippo+r downstream on doubleref k=0.2" checkpoint_path=""
# python src/main.py --config=ippo_ues_down  --env-config=doubleref_ood_test_02 with load_step=1000000 notes="ippo+ues downstream on doubleref k=0.2" checkpoint_path=""
# python src/main.py --config=ippo_uesr_down --env-config=doubleref_ood_test_02 with load_step=1000000 notes="ippo+uesr downstream on doubleref k=0.2" checkpoint_path=""
# python src/main.py --config=ippo_down      --env-config=doubleref_ood_test_04 with load_step=1000000 notes="ippo downstream on doubleref k=0.4" checkpoint_path=""
# python src/main.py --config=ippo_r_down    --env-config=doubleref_ood_test_04 with load_step=1000000 notes="ippo+r downstream on doubleref k=0.4" checkpoint_path=""
# python src/main.py --config=ippo_ues_down  --env-config=doubleref_ood_test_04 with load_step=1000000 notes="ippo+ues downstream on doubleref k=0.4" checkpoint_path=""
# python src/main.py --config=ippo_uesr_down --env-config=doubleref_ood_test_04 with load_step=1000000 notes="ippo+uesr downstream on doubleref k=0.4" checkpoint_path=""
# python src/main.py --config=ippo_down      --env-config=doubleref_ood_test_06 with load_step=1000000 notes="ippo downstream on doubleref k=0.6" checkpoint_path=""
# python src/main.py --config=ippo_r_down    --env-config=doubleref_ood_test_06 with load_step=1000000 notes="ippo+r downstream on doubleref k=0.6" checkpoint_path=""
# python src/main.py --config=ippo_ues_down  --env-config=doubleref_ood_test_06 with load_step=1000000 notes="ippo+ues downstream on doubleref k=0.6" checkpoint_path=""
# python src/main.py --config=ippo_uesr_down --env-config=doubleref_ood_test_06 with load_step=1000000 notes="ippo+uesr downstream on doubleref k=0.6" checkpoint_path=""
# python src/main.py --config=ippo_down      --env-config=doubleref_ood_test_08 with load_step=1000000 notes="ippo downstream on doubleref k=0.8" checkpoint_path=""
# python src/main.py --config=ippo_r_down    --env-config=doubleref_ood_test_08 with load_step=1000000 notes="ippo+r downstream on doubleref k=0.8" checkpoint_path=""
# python src/main.py --config=ippo_ues_down  --env-config=doubleref_ood_test_08 with load_step=1000000 notes="ippo+ues downstream on doubleref k=0.8" checkpoint_path=""
# python src/main.py --config=ippo_uesr_down --env-config=doubleref_ood_test_08 with load_step=1000000 notes="ippo+uesr downstream on doubleref k=0.8" checkpoint_path=""